import ThemeRegistry from '@/theme/ThemeRegistry';
import './globals.css';
import type { Metadata } from 'next';
import { Albert_Sans } from 'next/font/google';
import { ReactNode } from 'react';

const albertSans = Albert_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Portfolio - Aimee Laws',
  description: 'Generated by Aimee Laws',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className={`text-primary-950 ${albertSans.className}`}>
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  )
}
