import ThemeRegistry from '@/theme/ThemeRegistry';
import './globals.css';
import type { Metadata } from 'next';
import { Albert_Sans } from 'next/font/google';
import Link from 'next/link';
import { ReactNode } from 'react';
import NavDrawer from '@/components/NavDrawer';

const albertSans = Albert_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
  preload: true
});

export const metadata: Metadata = {
  title: 'Portfolio - Aimee Laws',
  description: 'Generated by Aimee Laws',
}

const pages = [
  {
    page: 'Home',
    url: '/'
  },
  {
    page: 'Skills',
    url: '/skills'
  },
  {
    page: 'Experience',
    url: '/experience'
  }
];

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className={`text-primary-950 ${albertSans.className}`}>
        <header className="w-full h-10 sm:h-16 bg-primary-50">
          <nav className="navigation absolute right-0 flex justify-end sm:mx-5">
            {pages.map(({ page, url }) => (
              <Link
                key={page}
                href={url}
                className="hidden sm:block px-4 py-5 no-underline text-primary-950"
              >
                {page}
              </Link>
            ))}

            <NavDrawer pages={pages} />
          </nav>
        </header>
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
